### ISSUE TITLE
Not compiling properly

### ISSUE THREAD

**Issue by jzgdev** [lljxx1/Dev4eos#4]
`api.voter.eosmedi.com:8087/complie:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED`

I'm taking a shot in the dark here, but perhaps it should be pointing to `compile` instead of `complie`?

**Comment by lljxx1** [comment]
thanks for u report, sorry for leave this project too many days.

**Comment by jzgdev** [comment]
:/ that's too bad. Seems very cool, would be great if you released the src on github if you are no longer developing.

**Comment by lljxx1** [comment]
ok, I think i will do that.
now it's woking, try to clean the site cache
